[build]
  publish = "public"
  command = "npm run build"
  functions = ""
[build.environment]
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--production"
  NODE_ENV = "production"

[[plugins]]
package = "netlify-plugin-gatsby-cache"
