localhost_development:
  backend:
    name: file-system
    api_root: /api

backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads
display_url: https://www.isabelsommerfeld.com
logo_url: /img/apple-touch-icon.png

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: 'blog'
    label: 'Blogg'
    label_singular: 'Bloggpost'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - {
          label: 'URL',
          name: 'url',
          widget: 'hidden',
          default: '',
        }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { 
          label: 'Dold',
          name: 'hidden',
          widget: 'boolean',
          default: false,
          hint: 'Om du vill spara utan att publicera kan du göra artikeln dold här.',
      }
      - { 
          label: 'Språk',
          name: 'language',
          widget: 'select',
          default: 'sv',
          options: [{ label: "Svenska", value: "sv" }, { label: "Engelska", value: "en" }],
      }
      - {
          label: 'Datum',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          default: null,
        }
      - {
          label: 'Utvald bild',
          name: 'featuredimage',
          widget: image,
          required: false,
          default: null,
          hint: 'Bild som visas i listningar, ex. på startsidan.'
        }
      - { label: 'Huvudinnehåll', name: 'body', widget: 'markdown' }
      - { label: 'Taggar', label_singular: 'Tagg', name: 'tags', widget: 'list', required: false }

  - name: 'pages'
    label: 'Sidor'
    label_singular: 'Sida'
    delete: false
    files:
      - file: 'src/pages/index.md'
        label: 'Landningssida'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Bild, name: image, widget: image }
          - { label: Rubrik, name: heading, widget: string, hint: 'Används också som titel på hela sajten' }
          - { label: Underrrubrik, name: subheading, widget: string }
          - { label: Beskrivning, name: body, widget: markdown }
          - { label: Sajtbeskrivning, name: description, widget: string, hint: 'Syns inte på landningssidan, men används som beskrivning för hela sajten, exempelvis i Googles sökresultat.'}
          
      - file: 'src/pages/om/index.md'
        label: 'Om mig'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Bild', name: 'image', widget: 'image' }
          - { label: 'Huvudinnehåll', name: 'body', widget: 'markdown' }

      - file: 'src/pages/publicerat/index.md'
        label: 'Publicerat'
        name: 'published'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'published-page',
            }
          - { label: 'Huvudinnehåll', name: 'body', widget: 'markdown' }

      - file: 'src/pages/pressbilder/index.md'
        label: 'Pressbilder'
        name: 'pressimages'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'pressimages-page',
            }          
          - { label: 'Huvudinnehåll', name: 'body', widget: 'markdown' }
          - label: 'Nerladdningsbara bilder'
            label_singular: 'Nerladdningsbar bild'
            name: 'downloadableimages'
            widget: 'list'
            hint: 'Bilder som besökaren kan ladda ner. OBS! Layouten och bildernas dimentioner är inte tillgängliga i förhandsgranskningen.'
            field: { label: Bild, name: downloadableimage, widget: image }
